# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  workflow_dispatch:
jobs:
  # This workflow contains a single job called "build"
  build-win:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Download Aftman
        uses: robinraju/release-downloader@v1.9
        with:
          repository: "https://github.com/LPGhatguy/aftman"
          latest: true
          extract: true
      - name: Install Aftman and darklua
        run: |
            "./aftman self-install"
            "aftman add seaofvoices/darklua"
      - name: Download Lune
        run: "aftman add lune-org/lune"
      - name: Bulid .EXE
        run: |
            "darklua process main.luau bulit.luau"
            "lune bulid bulit.luau"
      - name: Create Release
        uses: ncipollo/release-action@v1.14.0
        with:
          draft: true
          artifacts: "bulit.exe"
          
        
