# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  workflow_dispatch:
permissions:
  contents: write
defaults:
  run:
    working-directory: D:\\a\\bloxPackage\\bloxPackage
jobs:
  # This workflow contains a single job called "build"
  build-win:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under D:\\a\\bloxPackage\\bloxPackage, so your job can access it
      - uses: actions/checkout@v3
      - name: Download Aftman
        uses: robinraju/release-downloader@v1.9
        with:
          repository: "LPGhatguy/aftman"
          latest: true
          extract: true
      - name: Install Aftman and packages
        run: |
            "aftman add seaofvoices/darklua"
            "aftman add lune-org/lune"
      - name: Bulid .EXE
        run: |
            "mkdir bulid"
            "cd bulid"
            "darklua process main.luau bulid\\bulit.luau"
            "lune bulid bulid\\bulit.luau"
      - name: Read version file
        uses: actions/github-script@v7
        id: read_file
        with:
          result-encoding: string
          script: return require("node:fs").readFileSync("version.txt","utf8")
      - run: "dir -r D:\\"
      - name: Create Release
        uses: ncipollo/release-action@v1.14.0
        with:
          draft: true
          tag: ${{steps.read_file.outputs.result}}
          artifacts: "D:\\a\\bloxPackage\\bloxPackage\\bulit.exe"
          
        
